trigger: none   # manual runs only, for now

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm ci
    npm install -g @vscode/vsce@latest
  displayName: 'Install dependencies'

- script: vsce package
  displayName: 'Package extension'

- task: AzureCLI@2
  displayName: 'Publish to Marketplace'
  inputs:
    azureSubscription: G-Code_Azure
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      vsce publish --azure-credential
